receivers:
  otlp:
    protocols:
      grpc:
        # Убедитесь, что TLS не включен
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: "http://otel-collector:4317"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]