// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WasteIntoCity.Persistance;

#nullable disable

namespace WasteIntoCity.Persistance.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20250320231724_add_coordinates_report_complexity_type_start_datetime")]
    partial class add_coordinates_report_complexity_type_start_datetime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.AdminSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AcceptableDifferenceReportTrashcanOccupancy")
                        .HasColumnType("int")
                        .HasColumnName("acceptable_difference_report_trashcan_occupancy");

                    b.Property<int>("FalseComplaintFromAdditionRanking")
                        .HasColumnType("int")
                        .HasColumnName("false_complaint_from_addition_ranking");

                    b.Property<int>("FalseReportTrashcansOccupancyAdditionRanking")
                        .HasColumnType("int")
                        .HasColumnName("false_report_trashcans_occupancy_addition_ranking");

                    b.Property<int>("TrueComplaintFromAdditionRanking")
                        .HasColumnType("int")
                        .HasColumnName("true_complaint_from_addition_ranking");

                    b.Property<int>("TrueComplaintToAdditionRanking")
                        .HasColumnType("int")
                        .HasColumnName("true_complaint_to_addition_ranking");

                    b.HasKey("Id");

                    b.ToTable("admin_settings", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.CoordinatesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lat");

                    b.Property<string>("Lng")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lng");

                    b.HasKey("Id");

                    b.ToTable("coordinates", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.ImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("WorkApplicationsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_applications_id");

                    b.Property<Guid?>("WorkReportComplaintsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workReport_complaints_id");

                    b.Property<Guid?>("WorkReportResultsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_report_results_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkApplicationsId");

                    b.HasIndex("WorkReportComplaintsId");

                    b.HasIndex("WorkReportResultsId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FromUsersId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("from_users_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<Guid>("ToUsersId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("to_users_id");

                    b.HasKey("Id");

                    b.HasIndex("FromUsersId");

                    b.HasIndex("ToUsersId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("value");

                    b.Property<DateTime>("CreationTimestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("creation_timestamp");

                    b.Property<DateTime>("ExpirationTimestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiration_timestamp");

                    b.Property<bool>("Invalidated")
                        .HasColumnType("bit")
                        .HasColumnName("invalidated");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("jwt_id");

                    b.Property<bool>("Used")
                        .HasColumnType("bit")
                        .HasColumnName("used");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Value");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.TrashcanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AverageTrashcanOccupancyTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("average_trashcan_occupancy_type_id");

                    b.Property<int>("CoordinatesId")
                        .HasColumnType("int")
                        .HasColumnName("coordinates_id");

                    b.Property<Guid>("TrashcanTypesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trashcan_types_id");

                    b.Property<int>("Volume")
                        .HasColumnType("int")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("AverageTrashcanOccupancyTypeId");

                    b.HasIndex("CoordinatesId");

                    b.HasIndex("TrashcanTypesId");

                    b.ToTable("trashcans", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.TrashcanOccupancyTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("trashcan_occupancy_types", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.TrashcanPointReportEachMarkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("TrashcanOccupancyTypesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trashcan_occupancy_types_id");

                    b.Property<Guid>("TrashcanPointReportsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trashcan_point_reports_id");

                    b.Property<Guid>("TrashcansId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trashcans_id");

                    b.HasKey("Id");

                    b.HasIndex("TrashcanOccupancyTypesId");

                    b.HasIndex("TrashcanPointReportsId");

                    b.HasIndex("TrashcansId")
                        .IsUnique();

                    b.ToTable("trashcan_point_report_each_mark", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.TrashcanPointReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CoordinatesId")
                        .HasColumnType("int")
                        .HasColumnName("coordinates_id");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("submission_time");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("users_id");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatesId");

                    b.HasIndex("UsersId");

                    b.ToTable("trashcan_point_reports", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.TrashcanTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("trashcan_types", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.UserAccordingRoleEntity", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("user_according_roles", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("Ranking")
                        .HasColumnType("int")
                        .HasColumnName("ranking");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CoordinatesId")
                        .HasColumnType("int")
                        .HasColumnName("coordinates_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("StartedDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkComplexitiesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_complexities_id");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatesId");

                    b.HasIndex("WorkComplexitiesId");

                    b.ToTable("work_applications", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkColleagueReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AboutColleagueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("about_colleague_id");

                    b.Property<Guid>("FromParticipantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("from_participant_id");

                    b.Property<Guid>("WorkMarkTypesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_mark_types_id");

                    b.Property<Guid>("WorksId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("works_id");

                    b.HasKey("Id");

                    b.HasIndex("AboutColleagueId");

                    b.HasIndex("FromParticipantId");

                    b.HasIndex("WorkMarkTypesId");

                    b.HasIndex("WorksId");

                    b.ToTable("work_colleague_reports", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkComplexityTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int")
                        .HasColumnName("duration_hours");

                    b.Property<int>("MultiplierRanking")
                        .HasColumnType("int")
                        .HasColumnName("multiplier_ranking");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("ParticipantsMax")
                        .HasColumnType("int")
                        .HasColumnName("participants_max");

                    b.Property<int>("ParticipantsMin")
                        .HasColumnType("int")
                        .HasColumnName("participants_min");

                    b.Property<int>("RadiusOnMap")
                        .HasColumnType("int")
                        .HasColumnName("radius_on_map");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("work_complexity_types", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("CoordinatesId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("FinishDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("finish_datetime");

                    b.Property<DateTime>("StartedDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkComplexityTypesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_complexity_id");

                    b.Property<Guid>("WorkStatusTypesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_statuses_id");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatesId");

                    b.HasIndex("WorkComplexityTypesId");

                    b.HasIndex("WorkStatusTypesId");

                    b.ToTable("works", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkMarkTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AdditionRanking")
                        .HasColumnType("int")
                        .HasColumnName("addition_ranking");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("work_mark_types", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkParticipantEntity", b =>
                {
                    b.Property<Guid>("WorksId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("works_id");

                    b.Property<Guid>("ParticipantsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("participants_id");

                    b.HasKey("WorksId", "ParticipantsId");

                    b.HasIndex("ParticipantsId");

                    b.ToTable("work_participants", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkReportComplaintEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FromUsersId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("from_users_id");

                    b.Property<DateTime>("StartedDatime")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<int>("WorkReportComplaintTypesId")
                        .HasColumnType("int")
                        .HasColumnName("work_report_complaint_types_id");

                    b.Property<Guid>("WorksId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("works_id");

                    b.HasKey("Id");

                    b.HasIndex("FromUsersId");

                    b.HasIndex("WorkReportComplaintTypesId");

                    b.HasIndex("WorksId");

                    b.ToTable("work_report_complaints", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkReportComplaintTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("work_report_complaint_types", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkReportResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FromParticipantsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("from_participant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkStatusTypesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_statuses_id");

                    b.HasKey("Id");

                    b.HasIndex("FromParticipantsId");

                    b.HasIndex("WorkStatusTypesId");

                    b.ToTable("work_report_results", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkStatusTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("MultiplierRanking")
                        .HasColumnType("int")
                        .HasColumnName("multiplier_ranking");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("work_status_types", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.ImageEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.WorkApplicationEntity", "WorkApplication")
                        .WithMany("Images")
                        .HasForeignKey("WorkApplicationsId");

                    b.HasOne("WasteIntoCity.Persistance.Entities.WorkReportComplaintEntity", "WorkReportComplaint")
                        .WithMany("Images")
                        .HasForeignKey("WorkReportComplaintsId");

                    b.HasOne("WasteIntoCity.Persistance.Entities.WorkReportResultEntity", "WorkReportResult")
                        .WithMany("Images")
                        .HasForeignKey("WorkReportResultsId");

                    b.Navigation("WorkApplication");

                    b.Navigation("WorkReportComplaint");

                    b.Navigation("WorkReportResult");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.NotificationEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.UserEntity", "FromUser")
                        .WithMany("NotificationsFrom")
                        .HasForeignKey("FromUsersId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.UserEntity", "ToUser")
                        .WithMany("NotificationsTo")
                        .HasForeignKey("ToUsersId")
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.UserEntity", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.TrashcanEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.TrashcanOccupancyTypeEntity", "AverageTrashcanOccupancyType")
                        .WithMany("Trashcans")
                        .HasForeignKey("AverageTrashcanOccupancyTypeId");

                    b.HasOne("WasteIntoCity.Persistance.Entities.CoordinatesEntity", "Coordinates")
                        .WithMany("Trashcans")
                        .HasForeignKey("CoordinatesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.TrashcanTypeEntity", "TrashcanType")
                        .WithMany("Trashcans")
                        .HasForeignKey("TrashcanTypesId")
                        .IsRequired();

                    b.Navigation("AverageTrashcanOccupancyType");

                    b.Navigation("Coordinates");

                    b.Navigation("TrashcanType");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.TrashcanPointReportEachMarkEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.TrashcanOccupancyTypeEntity", "TrashcanOccupancyType")
                        .WithMany("TrashcanPointReportEachMarkList")
                        .HasForeignKey("TrashcanOccupancyTypesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.TrashcanPointReportEntity", "TrashcanPointReport")
                        .WithMany("TrashcanPointReportEachMarkList")
                        .HasForeignKey("TrashcanPointReportsId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.TrashcanEntity", "Trashcan")
                        .WithOne("TrashcanPointReportEachMark")
                        .HasForeignKey("WasteIntoCity.Persistance.Entities.TrashcanPointReportEachMarkEntity", "TrashcansId")
                        .IsRequired();

                    b.Navigation("Trashcan");

                    b.Navigation("TrashcanOccupancyType");

                    b.Navigation("TrashcanPointReport");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.TrashcanPointReportEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.CoordinatesEntity", "Coordinates")
                        .WithMany("TrashcanPointReports")
                        .HasForeignKey("CoordinatesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.UserEntity", "User")
                        .WithMany("TrashcanPointReports")
                        .HasForeignKey("UsersId")
                        .IsRequired();

                    b.Navigation("Coordinates");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.UserAccordingRoleEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .IsRequired();
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkApplicationEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.CoordinatesEntity", "Coordinates")
                        .WithMany("WorkApplications")
                        .HasForeignKey("CoordinatesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.WorkComplexityTypeEntity", "WorkComplexityType")
                        .WithMany("WorkApplications")
                        .HasForeignKey("WorkComplexitiesId")
                        .IsRequired();

                    b.Navigation("Coordinates");

                    b.Navigation("WorkComplexityType");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkColleagueReportEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.UserEntity", "UserAboutColleague")
                        .WithMany("WorkColleagueReportsAbout")
                        .HasForeignKey("AboutColleagueId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.UserEntity", "UserFromParticipant")
                        .WithMany("WorkColleagueReportsFrom")
                        .HasForeignKey("FromParticipantId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.WorkMarkTypeEntity", "WorkMarkType")
                        .WithMany("WorkColleagueReports")
                        .HasForeignKey("WorkMarkTypesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.WorkEntity", "Work")
                        .WithMany("WorkColleagueReports")
                        .HasForeignKey("WorksId")
                        .IsRequired();

                    b.Navigation("UserAboutColleague");

                    b.Navigation("UserFromParticipant");

                    b.Navigation("Work");

                    b.Navigation("WorkMarkType");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.CoordinatesEntity", "Coordinates")
                        .WithMany("Works")
                        .HasForeignKey("CoordinatesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.WorkComplexityTypeEntity", "WorkComplexityType")
                        .WithMany("Works")
                        .HasForeignKey("WorkComplexityTypesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.WorkStatusTypeEntity", "WorkStatusType")
                        .WithMany("Works")
                        .HasForeignKey("WorkStatusTypesId")
                        .IsRequired();

                    b.Navigation("Coordinates");

                    b.Navigation("WorkComplexityType");

                    b.Navigation("WorkStatusType");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkParticipantEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.WorkEntity", null)
                        .WithMany()
                        .HasForeignKey("WorksId")
                        .IsRequired();
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkReportComplaintEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.UserEntity", "FromUser")
                        .WithMany("WorkReportComplaints")
                        .HasForeignKey("FromUsersId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.WorkReportComplaintTypeEntity", "WorkReportComplaintType")
                        .WithMany("WorkReportComplaints")
                        .HasForeignKey("WorkReportComplaintTypesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.WorkEntity", "Work")
                        .WithMany("WorkReportComplaints")
                        .HasForeignKey("WorksId")
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("Work");

                    b.Navigation("WorkReportComplaintType");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkReportResultEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Persistance.Entities.UserEntity", "FromParticipant")
                        .WithMany("WorkReportResults")
                        .HasForeignKey("FromParticipantsId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Persistance.Entities.WorkStatusTypeEntity", "WorkStatusType")
                        .WithMany("WorkReportResults")
                        .HasForeignKey("WorkStatusTypesId")
                        .IsRequired();

                    b.Navigation("FromParticipant");

                    b.Navigation("WorkStatusType");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.CoordinatesEntity", b =>
                {
                    b.Navigation("TrashcanPointReports");

                    b.Navigation("Trashcans");

                    b.Navigation("WorkApplications");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.TrashcanEntity", b =>
                {
                    b.Navigation("TrashcanPointReportEachMark");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.TrashcanOccupancyTypeEntity", b =>
                {
                    b.Navigation("TrashcanPointReportEachMarkList");

                    b.Navigation("Trashcans");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.TrashcanPointReportEntity", b =>
                {
                    b.Navigation("TrashcanPointReportEachMarkList");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.TrashcanTypeEntity", b =>
                {
                    b.Navigation("Trashcans");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.UserEntity", b =>
                {
                    b.Navigation("NotificationsFrom");

                    b.Navigation("NotificationsTo");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TrashcanPointReports");

                    b.Navigation("WorkColleagueReportsAbout");

                    b.Navigation("WorkColleagueReportsFrom");

                    b.Navigation("WorkReportComplaints");

                    b.Navigation("WorkReportResults");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkApplicationEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkComplexityTypeEntity", b =>
                {
                    b.Navigation("WorkApplications");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkEntity", b =>
                {
                    b.Navigation("WorkColleagueReports");

                    b.Navigation("WorkReportComplaints");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkMarkTypeEntity", b =>
                {
                    b.Navigation("WorkColleagueReports");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkReportComplaintEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkReportComplaintTypeEntity", b =>
                {
                    b.Navigation("WorkReportComplaints");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkReportResultEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.WorkStatusTypeEntity", b =>
                {
                    b.Navigation("WorkReportResults");

                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
