// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WasteIntoCity.Persistance;

#nullable disable

namespace WasteIntoCity.Persistance.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WasteIntoCity.Core.Models.AccessTokenEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ExpirationTimestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiration_timestamp");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("value");

                    b.HasKey("UserId");

                    b.ToTable("access_tokens", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.ImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid?>("WorkApplicationsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_applications_id");

                    b.Property<Guid?>("WorkReportComplaintsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workReport_complaints_id");

                    b.Property<Guid?>("WorkReportResultsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_report_results_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkApplicationsId");

                    b.HasIndex("WorkReportComplaintsId");

                    b.HasIndex("WorkReportResultsId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FromUsersId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("from_users_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<Guid>("ToUsersId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("to_users_id");

                    b.HasKey("Id");

                    b.HasIndex("FromUsersId");

                    b.HasIndex("ToUsersId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("ExpirationTimestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiration_timestamp");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("value");

                    b.HasKey("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AverageTrashcanOccupancyTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("average_trashcan_occupancy_type_id");

                    b.Property<Guid>("TrashcanPointsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trashcan_points_id");

                    b.Property<Guid>("TrashcanTypesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trashcan_types_id");

                    b.Property<int>("Volume")
                        .HasColumnType("int")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("AverageTrashcanOccupancyTypeId");

                    b.HasIndex("TrashcanPointsId");

                    b.HasIndex("TrashcanTypesId");

                    b.ToTable("trashcans", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanOccupancyTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("trashcan_occupancy_types", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanPointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Lat")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lat");

                    b.Property<string>("Lng")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lng");

                    b.HasKey("Id");

                    b.ToTable("trashcan_points", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanPointReportEachMarkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("TrashcanOccupancyTypesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trashcan_occupancy_types_id");

                    b.Property<Guid>("TrashcanPointReportsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trashcan_point_reports_id");

                    b.Property<Guid>("TrashcansId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trashcans_id");

                    b.HasKey("Id");

                    b.HasIndex("TrashcanOccupancyTypesId");

                    b.HasIndex("TrashcanPointReportsId");

                    b.HasIndex("TrashcansId")
                        .IsUnique();

                    b.ToTable("trashcan_point_report_each_mark", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanPointReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("submission_time");

                    b.Property<Guid>("TrashcanPointsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trashcan_points_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("users_id");

                    b.HasKey("Id");

                    b.HasIndex("TrashcanPointsId");

                    b.HasIndex("UsersId");

                    b.ToTable("trashcan_point_reports", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("trashcan_types", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.UserAccordingRoleEntity", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int")
                        .HasColumnName("roles_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("user_according_roles", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("Ranking")
                        .HasColumnType("int")
                        .HasColumnName("ranking");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkApplicationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkComplexitiesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_complexities_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkComplexitiesId");

                    b.ToTable("work_applications", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkColleagueReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AboutColleagueId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("about_colleague_id");

                    b.Property<Guid>("FromParticipantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("from_participant_id");

                    b.Property<Guid>("WorkMarkTypesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_mark_types_id");

                    b.Property<Guid>("WorksId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("works_id");

                    b.HasKey("Id");

                    b.HasIndex("AboutColleagueId");

                    b.HasIndex("FromParticipantId");

                    b.HasIndex("WorkMarkTypesId");

                    b.HasIndex("WorksId");

                    b.ToTable("work_colleague_reports", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkComplexityTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int")
                        .HasColumnName("duration_hours");

                    b.Property<int>("MultiplierRanking")
                        .HasColumnType("int")
                        .HasColumnName("multiplier_ranking");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("ParticipantsMax")
                        .HasColumnType("int")
                        .HasColumnName("participants_max");

                    b.Property<int>("ParticipantsMin")
                        .HasColumnType("int")
                        .HasColumnName("participants_min");

                    b.Property<int>("RadiusOnMap")
                        .HasColumnType("int")
                        .HasColumnName("radius_on_map");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("work_complexity_types", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("FinishDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("finish_datetime");

                    b.Property<DateTime>("StartedDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_datetime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkComplexityTypesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_complexity_id");

                    b.Property<Guid>("WorkStatusTypesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_statuses_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkComplexityTypesId");

                    b.HasIndex("WorkStatusTypesId");

                    b.ToTable("works", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkMarkTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AdditionRanking")
                        .HasColumnType("int")
                        .HasColumnName("addition_ranking");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("work_mark_types", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkParticipantEntity", b =>
                {
                    b.Property<Guid>("WorksId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("works_id");

                    b.Property<Guid>("ParticipantsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("participants_id");

                    b.HasKey("WorksId", "ParticipantsId");

                    b.HasIndex("ParticipantsId");

                    b.ToTable("work_participants", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkReportComplaintEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FromUsersId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("from_users_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorksId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("works_id");

                    b.HasKey("Id");

                    b.HasIndex("FromUsersId");

                    b.HasIndex("WorksId");

                    b.ToTable("work_report_complaints", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkReportResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FromParticipantsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("from_participant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkStatusTypesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("work_statuses_id");

                    b.HasKey("Id");

                    b.HasIndex("FromParticipantsId");

                    b.HasIndex("WorkStatusTypesId");

                    b.ToTable("work_report_results", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkStatusTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("MultiplierRanking")
                        .HasColumnType("int")
                        .HasColumnName("multiplier_ranking");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("work_status_types", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Persistance.Entities.AdminSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AcceptableDifferenceReportTrashcanOccupancy")
                        .HasColumnType("int")
                        .HasColumnName("acceptable_difference_report_trashcan_occupancy");

                    b.Property<int>("FalseComplaintFromAdditionRanking")
                        .HasColumnType("int")
                        .HasColumnName("false_complaint_from_addition_ranking");

                    b.Property<int>("FalseReportTrashcansOccupancyAdditionRanking")
                        .HasColumnType("int")
                        .HasColumnName("false_report_trashcans_occupancy_addition_ranking");

                    b.Property<int>("TrueComplaintFromAdditionRanking")
                        .HasColumnType("int")
                        .HasColumnName("true_complaint_from_addition_ranking");

                    b.Property<int>("TrueComplaintToAdditionRanking")
                        .HasColumnType("int")
                        .HasColumnName("true_complaint_to_addition_ranking");

                    b.HasKey("Id");

                    b.ToTable("admin_settings", (string)null);
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.AccessTokenEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.UserEntity", "User")
                        .WithOne("AccessToken")
                        .HasForeignKey("WasteIntoCity.Core.Models.AccessTokenEntity", "UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.ImageEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.WorkApplicationEntity", "WorkApplication")
                        .WithMany("Images")
                        .HasForeignKey("WorkApplicationsId");

                    b.HasOne("WasteIntoCity.Core.Models.WorkReportComplaintEntity", "WorkReportComplaint")
                        .WithMany("Images")
                        .HasForeignKey("WorkReportComplaintsId");

                    b.HasOne("WasteIntoCity.Core.Models.WorkReportResultEntity", "WorkReportResult")
                        .WithMany("Images")
                        .HasForeignKey("WorkReportResultsId");

                    b.Navigation("WorkApplication");

                    b.Navigation("WorkReportComplaint");

                    b.Navigation("WorkReportResult");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.NotificationEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.UserEntity", "FromUser")
                        .WithMany("NotificationsFrom")
                        .HasForeignKey("FromUsersId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.UserEntity", "ToUser")
                        .WithMany("NotificationsTo")
                        .HasForeignKey("ToUsersId")
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.RefreshTokenEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.UserEntity", "User")
                        .WithOne("RefreshToken")
                        .HasForeignKey("WasteIntoCity.Core.Models.RefreshTokenEntity", "UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.TrashcanOccupancyTypeEntity", "AverageTrashcanOccupancyType")
                        .WithMany("Trashcans")
                        .HasForeignKey("AverageTrashcanOccupancyTypeId");

                    b.HasOne("WasteIntoCity.Core.Models.TrashcanPointEntity", "TrashcanPoint")
                        .WithMany("Trashcans")
                        .HasForeignKey("TrashcanPointsId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.TrashcanTypeEntity", "TrashcanType")
                        .WithMany("Trashcans")
                        .HasForeignKey("TrashcanTypesId")
                        .IsRequired();

                    b.Navigation("AverageTrashcanOccupancyType");

                    b.Navigation("TrashcanPoint");

                    b.Navigation("TrashcanType");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanPointReportEachMarkEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.TrashcanOccupancyTypeEntity", "TrashcanOccupancyType")
                        .WithMany("TrashcanPointReportEachMarkList")
                        .HasForeignKey("TrashcanOccupancyTypesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.TrashcanPointReportEntity", "TrashcanPointReport")
                        .WithMany("TrashcanPointReportEachMarkList")
                        .HasForeignKey("TrashcanPointReportsId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.TrashcanEntity", "Trashcan")
                        .WithOne("TrashcanPointReportEachMark")
                        .HasForeignKey("WasteIntoCity.Core.Models.TrashcanPointReportEachMarkEntity", "TrashcansId")
                        .IsRequired();

                    b.Navigation("Trashcan");

                    b.Navigation("TrashcanOccupancyType");

                    b.Navigation("TrashcanPointReport");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanPointReportEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.TrashcanPointEntity", "TrashcanPoint")
                        .WithMany("TrashcanPointReports")
                        .HasForeignKey("TrashcanPointsId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.UserEntity", "User")
                        .WithMany("TrashcanPointReports")
                        .HasForeignKey("UsersId")
                        .IsRequired();

                    b.Navigation("TrashcanPoint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.UserAccordingRoleEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .IsRequired();
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkApplicationEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.WorkComplexityTypeEntity", "WorkComplexityType")
                        .WithMany("WorkApplications")
                        .HasForeignKey("WorkComplexitiesId")
                        .IsRequired();

                    b.Navigation("WorkComplexityType");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkColleagueReportEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.UserEntity", "UserAboutColleague")
                        .WithMany("WorkColleagueReportsAbout")
                        .HasForeignKey("AboutColleagueId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.UserEntity", "UserFromParticipant")
                        .WithMany("WorkColleagueReportsFrom")
                        .HasForeignKey("FromParticipantId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.WorkMarkTypeEntity", "WorkMarkType")
                        .WithMany("WorkColleagueReports")
                        .HasForeignKey("WorkMarkTypesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.WorkEntity", "Work")
                        .WithMany("WorkColleagueReports")
                        .HasForeignKey("WorksId")
                        .IsRequired();

                    b.Navigation("UserAboutColleague");

                    b.Navigation("UserFromParticipant");

                    b.Navigation("Work");

                    b.Navigation("WorkMarkType");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.WorkComplexityTypeEntity", "WorkComplexityType")
                        .WithMany("Works")
                        .HasForeignKey("WorkComplexityTypesId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.WorkStatusTypeEntity", "WorkStatusType")
                        .WithMany("Works")
                        .HasForeignKey("WorkStatusTypesId")
                        .IsRequired();

                    b.Navigation("WorkComplexityType");

                    b.Navigation("WorkStatusType");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkParticipantEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.WorkEntity", null)
                        .WithMany()
                        .HasForeignKey("WorksId")
                        .IsRequired();
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkReportComplaintEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.UserEntity", "FromUser")
                        .WithMany("WorkReportComplaints")
                        .HasForeignKey("FromUsersId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.WorkEntity", "Work")
                        .WithMany("WorkReportComplaints")
                        .HasForeignKey("WorksId")
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkReportResultEntity", b =>
                {
                    b.HasOne("WasteIntoCity.Core.Models.UserEntity", "FromParticipant")
                        .WithMany("WorkReportResults")
                        .HasForeignKey("FromParticipantsId")
                        .IsRequired();

                    b.HasOne("WasteIntoCity.Core.Models.WorkStatusTypeEntity", "WorkStatusType")
                        .WithMany("WorkReportResults")
                        .HasForeignKey("WorkStatusTypesId")
                        .IsRequired();

                    b.Navigation("FromParticipant");

                    b.Navigation("WorkStatusType");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanEntity", b =>
                {
                    b.Navigation("TrashcanPointReportEachMark");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanOccupancyTypeEntity", b =>
                {
                    b.Navigation("TrashcanPointReportEachMarkList");

                    b.Navigation("Trashcans");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanPointEntity", b =>
                {
                    b.Navigation("TrashcanPointReports");

                    b.Navigation("Trashcans");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanPointReportEntity", b =>
                {
                    b.Navigation("TrashcanPointReportEachMarkList");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.TrashcanTypeEntity", b =>
                {
                    b.Navigation("Trashcans");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.UserEntity", b =>
                {
                    b.Navigation("AccessToken");

                    b.Navigation("NotificationsFrom");

                    b.Navigation("NotificationsTo");

                    b.Navigation("RefreshToken");

                    b.Navigation("TrashcanPointReports");

                    b.Navigation("WorkColleagueReportsAbout");

                    b.Navigation("WorkColleagueReportsFrom");

                    b.Navigation("WorkReportComplaints");

                    b.Navigation("WorkReportResults");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkApplicationEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkComplexityTypeEntity", b =>
                {
                    b.Navigation("WorkApplications");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkEntity", b =>
                {
                    b.Navigation("WorkColleagueReports");

                    b.Navigation("WorkReportComplaints");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkMarkTypeEntity", b =>
                {
                    b.Navigation("WorkColleagueReports");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkReportComplaintEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkReportResultEntity", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WasteIntoCity.Core.Models.WorkStatusTypeEntity", b =>
                {
                    b.Navigation("WorkReportResults");

                    b.Navigation("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
